# Generated by Django 2.0.7 on 2018-10-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('place', models.TextField()),
                ('cwl', models.FloatField()),
                ('dwl', models.FloatField()),
            ],
        ),
    ]
